# Cleaning data

In [6]:
import pandas as pd

In [7]:
data_dir="../data/education-data/raw/edstats-csv-zip-32-mb-"
df_data=pd.read_csv(f"{data_dir}/EdStatsData.csv")

In [3]:
id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code']
year_cols=[col for col in df_data.columns if col not in id_vars ]

In [ ]:
df_long = df_data.melt(
    id_vars=id_vars,
    value_vars=year_cols,
    var_name='Year',
    value_name='Value'
)

In [5]:
df_long.head(3)

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value
0,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2,1970,NaN
1,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.F,1970,NaN
2,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.GPI,1970,NaN

In [6]:
df_long.head(20)

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value
0,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2,1970,NaN
1,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.F,1970,NaN
2,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.GPI,1970,NaN
3,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.M,1970,NaN
4,Arab World,ARB,"Adjusted net enrolment rate, primary, both sex...",SE.PRM.TENR,1970,54.822121
5,Arab World,ARB,"Adjusted net enrolment rate, primary, female (%)",SE.PRM.TENR.FE,1970,43.351101
6,Arab World,ARB,"Adjusted net enrolment rate, primary, gender p...",UIS.NERA.1.GPI,1970,0.658570
7,Arab World,ARB,"Adjusted net enrolment rate, primary, male (%)",SE.PRM.TENR.MA,1970,65.826233
8,Arab World,ARB,"Adjusted net enrolment rate, upper secondary, ...",UIS.NERA.3,1970,NaN
9,Arab World,ARB,"Adjusted net enrolment rate, upper secondary, ...",UIS.NERA.3.F,1970,NaN
10,Arab World,ARB,"Adjusted net enrolment rate, upper secondary, ...",UIS.NERA.3.GPI,1970,NaN
11,Arab World,ARB,"Adjusted net enrolment rate, upper secondary, ...",UIS.NERA.3.M,1970,NaN
12,Arab World,ARB,Adjusted net intake rate to Grade 1 of primary...,UIS.NIRA.1,1970,52.448921
13,Arab World,ARB,Adjusted net intake rate to Grade 1 of primary...,UIS.NIRA.1.F,1970,44.342487
14,Arab World,ARB,Adjusted net intake rate to Grade 1 of primary...,UIS.NIRA.1.GPI,1970,0.736340
15,Arab World,ARB,Adjusted net intake rate to Grade 1 of primary...,UIS.NIRA.1.M,1970,60.220436
16,Arab World,ARB,"Adult illiterate population, 15+ years, % female",UIS.LPP.AG15T99,1970,NaN
17,Arab World,ARB,"Adult illiterate population, 15+ years, both s...",UIS.LP.AG15T99,1970,NaN
18,Arab World,ARB,"Adult illiterate population, 15+ years, female...",UIS.LP.AG15T99.F,1970,NaN
19,Arab World,ARB,"Adult illiterate population, 15+ years, male (...",UIS.LP.AG15T99.M,1970,NaN

In [7]:
df_malaysia=df_long[df_long['Country Name']=='Malaysia']

In [8]:
df_malaysia.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value
531425,Malaysia,MYS,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2,1970,52.333721
531426,Malaysia,MYS,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.F,1970,NaN
531427,Malaysia,MYS,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.GPI,1970,NaN
531428,Malaysia,MYS,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.M,1970,NaN
531429,Malaysia,MYS,"Adjusted net enrolment rate, primary, both sex...",SE.PRM.TENR,1970,NaN

In [9]:
df_malaysia['Value'].count()

26127

In [10]:
df_malaysia['Year'].isna().sum()

0

In [11]:
df_malaysia_clean = df_malaysia.dropna(subset=['Value']).copy()

In [12]:
df_malaysia_clean.count()

Country Name      26127
Country Code      26127
Indicator Name    26127
Indicator Code    26127
Year              26127
Value             26127
dtype: int64

In [13]:
result=df_malaysia_clean.loc[df_malaysia_clean['Indicator Name']=='Adjusted net enrolment rate, lower secondary, both sexes (%)',
['Indicator Name','Indicator Code']]

In [14]:
result.count()

Indicator Name    20
Indicator Code    20
dtype: int64

In [15]:
finance_keywords = ['expenditure', 'spending', 'gdp', 'gni', 'budget']